name: projet_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.14.1
  cupertino_icons: ^1.0.2
  firebase_core: ^2.23.0
  cloud_firestore: ^4.13.2
  firebase_storage: ^11.5.2
  image_picker: ^1.0.4
  cached_network_image: ^3.2.0
  tflite_flutter: ^0.10.3
  image: ^3.0.1
  progress_dialog_null_safe: ^1.0.7
  rename_app: ^1.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: 0.11.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
